spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///springboot_dubbo_email
dubbo:
  application:
    name: registor_service
  registry:
    address: zookeeper://192.168.226.188:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 10000
    retries: 3

