spring:
  mail:

    protocol: smtp

    host: smtp.qq.com

    username: 3134629631@qq.com

    password: zduajmxrfbdidcdd


dubbo:
  application:
    name: email_service
  registry:
    address: zookeeper://192.168.226.188:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 20000
    retries: 3




